<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>andino_firmware</name>
  <version>0.2.0</version>
  <description>
    Firmware sources for Arduino UNO R3 used with Andino. This package installs
    the firmware sources as share files (it is not flashed by colcon).
  </description>

  <maintainer email="noreply@example.com">MEPhI ROS2 drone</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
